$(document).ready(function(){
    $(".subnav-1").mouseover(function(){
        $(".subnav_article-1").slideDown();
    });
    $(".subnav-1").mouseleave(function(){
        $(".subnav_article-1").slideUp();
    });
    $(".subnav-2").mouseover(function(){
        $(".subnav_article-2").slideDown();
    });
    $(".subnav-2").mouseleave(function(){
        $(".subnav_article-2").slideUp();
    });
    $(".subnav-3").mouseover(function(){
        $(".subnav_article-3").slideDown();
    });
    $(".subnav-3").mouseleave(function(){
        $(".subnav_article-3").slideUp();
    });
    $(".subnav-4").mouseover(function(){
        $(".subnav_article-4").slideDown();
    });
    $(".subnav-4").mouseleave(function(){
        $(".subnav_article-4").slideUp();
    });
    $(".subnav-5").mouseover(function(){
        $(".subnav_article-5").slideDown();
    });
    $(".subnav-5").mouseleave(function(){
        $(".subnav_article-5").slideUp();
    });
    $(".subnav-6").mouseover(function(){
        $(".subnav_article-6").slideDown();
    });
    $(".subnav-6").mouseleave(function(){
        $(".subnav_article-6").slideUp();
    });
    
  });